# Generated by Django 5.2.1 on 2025-05-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='address',
            field=models.CharField(default='Generic Bank Address', max_length=32),
        ),
    ]
